-- Intentionally empty.
--
-- Local and clean-room databases are created from migrations only. If deterministic
-- demo fixtures are needed later, add synthetic INSERT statements that cannot
-- rewrite data copied from another environment.
