var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/leads/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11npv~_._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0pk1owb.js")
R.c("server/chunks/ssr/[root-of-the-server]__06u9q0k._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__033v0o2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(dashboard)_layout_tsx_027owf8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_leads_page_actions_0.j58-d.js")
R.m(22622)
module.exports=R.m(22622).exports
