// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contracts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contracts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/[id]/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/[id]/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/quotations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/quotations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/quotations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/quotations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/ads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/tasks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/tasks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/workbench/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workbench">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/workbench/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activities">> = Specific
  const handler = {} as typeof import("../../src/app/api/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity/daily-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity/daily-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity/daily-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/impersonate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ads/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ads/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/ads/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/dev-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/dev-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/dev-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/command-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/command-center">> = Specific
  const handler = {} as typeof import("../../src/app/api/command-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/confirm-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/confirm-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/confirm-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/remind-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/remind-payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/remind-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/revoke">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/[id]/upload-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/upload-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/[id]/upload-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cos/download-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cos/download-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/cos/download-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/check-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/check-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/check-no-answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-no-answer">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/check-no-answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/check-overdue-followups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-overdue-followups">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/check-overdue-followups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/check-overdue-installments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-overdue-installments">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/check-overdue-installments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/cleanup-notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/cleanup-notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/daily-funnel-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-funnel-snapshot">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/daily-funnel-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/daily-reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-reminder">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/daily-reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/ads-roi/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ads-roi/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/ads-roi/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/ads-roi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ads-roi">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/ads-roi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/lead-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/lead-health">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/lead-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/lead-sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/lead-sources">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/lead-sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/payment-tracker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/payment-tracker">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/payment-tracker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/pipeline-funnel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/pipeline-funnel">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/pipeline-funnel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/quality">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/sales-load/rebalance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/sales-load/rebalance">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/sales-load/rebalance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/sales-load/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/sales-load">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/sales-load/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/team-ownership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/team-ownership">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/team-ownership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/team-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/team-performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/team-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/weekly-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/weekly-review">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/weekly-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/weekly-trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/weekly-trends">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/weekly-trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow-ups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow-ups">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow-ups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hermes/generate-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hermes/generate-quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/hermes/generate-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hermes/knx-design/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hermes/knx-design">> = Specific
  const handler = {} as typeof import("../../src/app/api/hermes/knx-design/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hermes/knx-design/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hermes/knx-design/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/hermes/knx-design/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi/targets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi/targets">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi/targets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/contacts/[contactId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/contacts/[contactId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/contacts/[contactId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/follow-up/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/follow-up">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/follow-up/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/milestone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/milestone">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/milestone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/quality">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/stage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/stage">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/stage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/archive">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/follow-up-overdue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/follow-up-overdue">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/follow-up-overdue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/import/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/import/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/import/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/import/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/import/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/import/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/meta-capi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta-capi">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/meta-capi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/oauth-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/oauth-callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/oauth-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/daily/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/daily">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/daily/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/funnel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/funnel">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/funnel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/read-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/read-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/read-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/unread-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/allocate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]/allocate">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/allocate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotations/[id]/convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/[id]/convert">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotations/[id]/convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotations/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/calculate">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotations/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotations/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotations/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotations/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotations/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/data">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workbench/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workbench">> = Specific
  const handler = {} as typeof import("../../src/app/api/workbench/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
