var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/change-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oy2ii5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0zveci-.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~yg3t0._.js")
R.c("server/chunks/ssr/node_modules_12pcxnx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oinzxd._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/_00zu~09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_app_(auth)_layout_tsx_02wmo~m._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_change-password_page_actions_0vx~6-8.js")
R.m(72080)
module.exports=R.m(72080).exports
