var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/leads/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ac3s5.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_076bq-7.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~yg3t0._.js")
R.c("server/chunks/ssr/node_modules_12pcxnx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oinzxd._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/_00zu~09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_layout_tsx_027owf8._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_error_tsx_0emp5v-._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_loading_tsx_128m_w_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_leads_new_page_actions_0ltt7ox.js")
R.m(84240)
module.exports=R.m(84240).exports
