var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~or05y._.js")
R.c("server/chunks/ssr/09p__next_dist_esm_build_templates_app-page_08eux_5.js")
R.c("server/chunks/ssr/09p__next_dist_115vfx6._.js")
R.c("server/chunks/ssr/09p__08~7--3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a.0g25._.js")
R.c("server/chunks/ssr/09p__04vz3-h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0al884m._.js")
R.c("server/chunks/ssr/newme-platform_src_app_error_tsx_0x8soi5._.js")
R.c("server/chunks/ssr/newme-platform_src_app_not-found_tsx_0wax0mq._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_0~wrd2k._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_builtin_unauthorized_088m3fh.js")
R.c("server/chunks/ssr/newme-platform_src_app_global-error_tsx_0bawem4._.js")
R.c("server/chunks/ssr/newme-platform__next-internal_server_app_page_actions_0renkoy.js")
R.m(75205)
module.exports=R.m(75205).exports
