var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/change-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__08jecy~._.js")
R.c("server/chunks/ssr/09p__08~7--3._.js")
R.c("server/chunks/ssr/09p__next_dist_esm_build_templates_app-page_0vthjfy.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a.0g25._.js")
R.c("server/chunks/ssr/09p__04vz3-h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0al884m._.js")
R.c("server/chunks/ssr/newme-platform_src_app_error_tsx_0x8soi5._.js")
R.c("server/chunks/ssr/newme-platform_src_app_not-found_tsx_0wax0mq._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_0~wrd2k._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_builtin_unauthorized_088m3fh.js")
R.c("server/chunks/ssr/newme-platform_src_app_global-error_tsx_0bawem4._.js")
R.c("server/chunks/ssr/newme-platform_src_app_(auth)_layout_tsx_08jj871._.js")
R.c("server/chunks/ssr/0gg9__next-internal_server_app_(auth)_change-password_page_actions_0z6yquh.js")
R.m(98354)
module.exports=R.m(98354).exports
