var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ndwcqq._.js")
R.c("server/chunks/ssr/09p__08~7--3._.js")
R.c("server/chunks/ssr/09p__next_dist_esm_build_templates_app-page_0lmixuk.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a.0g25._.js")
R.c("server/chunks/ssr/09p__04vz3-h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0al884m._.js")
R.c("server/chunks/ssr/newme-platform_src_app_error_tsx_0x8soi5._.js")
R.c("server/chunks/ssr/newme-platform_src_app_not-found_tsx_0wax0mq._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_0~wrd2k._.js")
R.c("server/chunks/ssr/09p__next_dist_client_components_builtin_unauthorized_088m3fh.js")
R.c("server/chunks/ssr/newme-platform_src_app_global-error_tsx_0bawem4._.js")
R.c("server/chunks/ssr/newme-platform_src_app_(dashboard)_layout_tsx_021.bj5._.js")
R.c("server/chunks/ssr/newme-platform_src_app_(dashboard)_error_tsx_0p0q8~r._.js")
R.c("server/chunks/ssr/newme-platform_src_app_(dashboard)_loading_tsx_00hm78s._.js")
R.c("server/chunks/ssr/0gg9__next-internal_server_app_(dashboard)_dashboard_page_actions_0wesgu2.js")
R.m(76065)
module.exports=R.m(76065).exports
