;!function(){try { var e="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof global?global:"undefined"!=typeof window?window:"undefined"!=typeof self?self:{},n=(new e.Error).stack;n&&((e._debugIds|| (e._debugIds={}))[n]="107ec7ac-4c40-5d64-c672-54ade9aa8af8")}catch(e){}}();
module.exports=[93695,(a,b,c)=>{b.exports=a.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},50640,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"InvariantError",{enumerable:!0,get:function(){return d}});class d extends Error{constructor(a,b){super(`Invariant: ${a.endsWith(".")?a:a+"."} This is a bug in Next.js.`,b),this.name="InvariantError"}}},10585,a=>{a.v("/_next/static/media/favicon.0x3dzn~oxb6tn.ico"+(globalThis.NEXT_CLIENT_ASSET_SUFFIX||""))},68611,a=>{"use strict";let b={src:a.i(10585).default,width:256,height:256};a.s(["default",0,b])},12350,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/src/app/(dashboard)/projects/projects-client.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/src/app/(dashboard)/projects/projects-client.tsx <module evaluation>","default")},857,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/src/app/(dashboard)/projects/projects-client.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/src/app/(dashboard)/projects/projects-client.tsx","default")},23681,a=>{"use strict";a.i(12350);var b=a.i(857);a.n(b)},99378,a=>{"use strict";var b=a.i(7997);a.i(70396);var c=a.i(73727),d=a.i(70891),e=a.i(23681);async function f(){let a=await (0,d.createServerSupabase)(),{data:{user:b},error:e}=await a.auth.getUser();(e||!b)&&(0,c.redirect)("/login");let{data:f}=await a.from("profiles").select("role").eq("id",b.id).single();return f&&["admin","boss","sales","operator"].includes(f.role)||(0,c.redirect)("/dashboard"),{user:b,role:f.role}}async function g(){let{user:a,role:c}=await f(),g=[],h=null;try{let b=(await (0,d.createServerSupabase)()).from("projects").select(`
        *,
        customer:customers!customer_id(
          name,
          phone,
          lead:leads!lead_id(customer_name)
        ),
        assigned_profile:profiles!assigned_to(full_name)
      `);"sales"===c&&a&&(b=b.eq("assigned_to",a.id));let{data:e,error:f}=await b.order("created_at",{ascending:!1}).limit(500);if(f)throw f;e&&(g=e)}catch(a){console.error("Projects server fetch failed:",a?.message||a),h=a?.message||"common.failedToLoadProjects"}return(0,b.jsx)("div",{className:"space-y-4",children:(0,b.jsx)(e.default,{initialData:g,fetchError:h})})}a.s(["default",0,g,"dynamic",0,"force-dynamic"])},2694,a=>{a.n(a.i(99378))}];

//# debugId=107ec7ac-4c40-5d64-c672-54ade9aa8af8
//# sourceMappingURL=%5Broot-of-the-server%5D__01wby18._.js.map