var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/quotes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__130-~uo._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y7br-b.js")
R.c("server/chunks/ssr/[root-of-the-server]__06u9q0k._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__033v0o2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(dashboard)_layout_tsx_027owf8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_quotes_page_actions_08nhc2j.js")
R.m(14164)
module.exports=R.m(14164).exports
